### ISSUE TITLE
Build Support

### ISSUE THREAD

**Issue by sabrehagen** [tale/trap2#1]
Hi,

I have read the README.md caveat on build issues, however I wanted to request your support with building. I am getting the build error:

```
λ ninja -C build
ninja: Entering directory `build'
[13/27] Compiling C object trap2.p/src_term_render.c.o
FAILED: trap2.p/src_term_render.c.o
cc -Itrap2.p -I. -I.. -I../include -I../subprojects/glew-2.2.0/include -I../subprojects/glfw-3.3.8/include -I../subprojects/glfw-3.3.8/src -I../subprojects/vterm/include -I../subprojects/wgpu_native -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -fcolor-diagnostics -Wall -Winvalid-pch -std=c11 -O0 -g -DGL_SILENCE_DEPRECATION -F/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework -DGLEW_STATIC -MD -MQ trap2.p/src_term_render.c.o -MF trap2.p/src_term_render.c.o.d -o trap2.p/src_term_render.c.o -c ../src/term/render.c
../src/term/render.c:65:71: error: no member named 'opacity' in 'config_t'
        render_glyph(&state->font, char_code, &coord, &color, state->config->opacity);
                                                              ~~~~~~~~~~~~~  ^
../src/term/render.c:69:39: error: no member named 'opacity' in 'config_t'
        glClearColor(0, 0, 0, state->config->opacity);
                              ~~~~~~~~~~~~~  ^
2 errors generated.
[17/27] Compiling C object trap2.p/src_term_handle.c.o
../src/term/handle.c:138:6: warning: variable 'vterm_modifier' set but not used [-Wunused-but-set-variable]
        int vterm_modifier = VTERM_MOD_NONE;
            ^
1 warning generated.
[25/27] Compiling C object subprojects/glfw-3.3.8/libglfw3.a.p/src_osmesa_context.c.o
ninja: build stopped: subcommand failed.
```

Would you kindly provide some direction on how to rectify this build failure?

**Comment by tale** [comment]
Hi, I realized that I didn't push something inside of `term.h`, you'll need to modify the `config_t` struct to include an opacity int. Also one more thing to keep in mind is that `main.c` will look for the shell path and font path that I've thrown in there. You'll need to change those to point to your own font and shell.

![CleanShot 2023-11-15 at 07 25 42@2x](https://github.com/tale/trap2/assets/46133336/5578a0c3-b870-4b75-ae57-57e8e4c70e89)

**Comment by sabrehagen** [comment]
> keep in mind is that main.c will look for the shell path and font path

I updated those, thanks.

When I run the build it searches for libraries in `/Users/tale/Developer/tale`. I searched your codebase for that string and can't find it. How is that path getting set?

```sh
> ./build/trap2
dyld[91201]: Library not loaded: /Users/tale/Developer/tale/sdl2/lib/libwgpu_native.dylib
  Referenced from: <272123A3-5503-328A-A0EC-AB5D0A33C96A> /Users/jackson.delahunt/repositories/tmp/trap2/build/trap2
  Reason: tried: '/Users/tale/Developer/tale/sdl2/lib/libwgpu_native.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/tale/Developer/tale/sdl2/lib/libwgpu_native.dylib' (no such file), '/Users/tale/Developer/tale/sdl2/lib/libwgpu_native.dylib' (no such file)
[1]    91201 abort      ./build/trap2
```

No matches other than binaries:

```sh
> grep -r 'Developer/tale' .       
ggrep: ./build/trap2: binary file matches
ggrep: ./subprojects/wgpu_native/libwgpu_native.dylib: binary file matches
```

**Comment by tale** [comment]
Ahh sorry, the libwgpu_native.dylib is hardcoded to that path.
Honestly, you don't need to link wgpu anyways since that's a future thing I haven't implemented yet, however the fix would be changing the path of the binary `@rpath` by running `install_name_tool -id <full_path_to_dylib> ./subprojects/wgpu_native/libwgpu_native.dylib`. You can confirm this worked by running `otool -L` again on `./subprojects/wgpu_native/libwgpu_native.dylib`. Sorry about that!

![CleanShot 2023-11-15 at 11 52 56@2x](https://github.com/tale/trap2/assets/46133336/324f8ed0-85a8-4f1c-bb91-e71f9b662f68)

**Comment by tale** [comment]
Try the latest commit, it hopefully fixes all of these issues.

**Comment by tale** [comment]
Switched to CMake in the latest commit.
